### ISSUE TITLE
每次喷图时都会出现这个报错，无法破坏和自动消失

### ISSUE THREAD

**Issue by BZxmxs** [LSDog/CustomSprays#19]
[版本：1.20.1]
 - 核心：[Spigot]
 - 插件版本：[e.g. 1.5.3]
### **报错**
[18:43:46] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.network.ServerCommonPacketListenerImpl
[18:43:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[18:43:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[18:43:46] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[18:43:46] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[18:43:46] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[18:43:46] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.util.NMS.getClass(NMS.java:32)
[18:43:46] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.util.NMS.getMcClass(NMS.java:80)
[18:43:46] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.util.NMS.getMcServerCommonPacketListenerImplClass(NMS.java:181)
[18:43:46] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.util.NMS.getMcPlayerNetworkManager(NMS.java:283)
[18:43:46] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.util.NMS.getMcPlayerNettyChannel(NMS.java:307)
[18:43:46] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.listener.PacketListener.removePlayer(PacketListener.java:37)
[18:43:46] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.listener.EventListener.onQuit(EventListener.java:60)
[18:43:46] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor356.execute(Unknown Source)
[18:43:46] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[18:43:46] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:43:46] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:53)
[18:43:46] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[18:43:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:785)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:766)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:2193)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2167)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.m(NetworkManager.java:819)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:254)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1600)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:456)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[18:43:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309)
[18:43:46] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:43:46] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to CustomSprays v1.5.11
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "fun.LSDog.CustomSprays.util.NMS.fPlayerConnection_networkManager" is null
	at fun.LSDog.CustomSprays.util.NMS.getMcPlayerNetworkManager(NMS.java:288) ~[CustomSprays.jar:?]
	at fun.LSDog.CustomSprays.util.NMS.getMcPlayerNettyChannel(NMS.java:307) ~[CustomSprays.jar:?]
	at fun.LSDog.CustomSprays.listener.PacketListener.removePlayer(PacketListener.java:37) ~[CustomSprays.jar:?]
	at fun.LSDog.CustomSprays.listener.EventListener.onQuit(EventListener.java:60) ~[CustomSprays.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor356.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:53) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:785) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:766) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2193) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2167) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:819) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1600) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:456) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:43:46] [Server thread/INFO]: shiliu_orz left the game
[18:44:14] [User Authenticator #21/INFO]: [GroupManager] Async Player Login event refresh data... 
[18:44:14] [User Authenticator #21/INFO]: [GroupManager] Async Player Login event finshed. 
[18:44:14] [User Authenticator #21/INFO]: UUID of player shiliu_awa is dbbb2326-2f2e-368f-891b-ffe8f51d9c0e
[18:44:14] [Server thread/INFO]: [CustomSprays][DEBUG] Injecting netty channel of shiliu_awa
[18:44:14] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.network.ServerCommonPacketListenerImpl
[18:44:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[18:44:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[18:44:14] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[18:44:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[18:44:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[18:44:14] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.util.NMS.getClass(NMS.java:32)
[18:44:14] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.util.NMS.getMcClass(NMS.java:80)
[18:44:14] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.util.NMS.getMcServerCommonPacketListenerImplClass(NMS.java:181)
[18:44:14] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.util.NMS.getMcPlayerNetworkManager(NMS.java:283)
[18:44:14] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.util.NMS.getMcPlayerNettyChannel(NMS.java:307)
[18:44:14] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.listener.PacketListener.addPlayer(PacketListener.java:22)
[18:44:14] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.listener.EventListener.playerJoin(EventListener.java:49)
[18:44:14] [Server thread/WARN]: 	at CustomSprays.jar//fun.LSDog.CustomSprays.listener.EventListener.onJoin(EventListener.java:36)
[18:44:14] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor357.execute(Unknown Source)
[18:44:14] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[18:44:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:44:14] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:53)
[18:44:14] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[18:44:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.a(PlayerList.java:449)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.server.network.LoginListener.a(LoginListener.java:203)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.server.network.LoginListener.d(LoginListener.java:184)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.server.network.LoginListener.c(LoginListener.java:86)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:603)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:234)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1600)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:456)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[18:44:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309)
[18:44:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:44:14] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CustomSprays v1.5.11
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "fun.LSDog.CustomSprays.util.NMS.fPlayerConnection_networkManager" is null
	at fun.LSDog.CustomSprays.util.NMS.getMcPlayerNetworkManager(NMS.java:288) ~[CustomSprays.jar:?]
	at fun.LSDog.CustomSprays.util.NMS.getMcPlayerNettyChannel(NMS.java:307) ~[CustomSprays.jar:?]
	at fun.LSDog.CustomSprays.listener.PacketListener.addPlayer(PacketListener.java:22) ~[CustomSprays.jar:?]
	at fun.LSDog.CustomSprays.listener.EventListener.playerJoin(EventListener.java:49) ~[CustomSprays.jar:?]
	at fun.LSDog.CustomSprays.listener.EventListener.onJoin(EventListener.java:36) ~[CustomSprays.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor357.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:53) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:449) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:203) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:184) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:86) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:603) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1600) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:456) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:44:14] [Server thread/INFO]: shiliu_awa joined the game

**Comment by BZxmxs** [comment]
看到这个报错真的很烦

**Comment by LSDog** [comment]
怎么Close了？问题解决了吗，还是点错了？

**Comment by BZxmxs** [comment]
点错了
