### ISSUE TITLE
Unknown disabling

### ISSUE THREAD

**Issue by deadspidervenom** [LSDog/CustomSprays#22]
In the latest 1.21 version on a 1.20.6 server, the plugin will be disabled on launch without any error in the server, if i try to use the command/s in game an error occurs telling me the plugin is disabled. If i go back one plugin version i get an error on load up and the server shows it was disabled.

If you have any issues understanding anything i have typed, do not hesitate to ask for help understanding.

Error for 1.21(latest) version
`[05:18:48] [Server thread/ERROR]: Command exception: /customsprays
org.bukkit.command.CommandException: Cannot execute command 'customsprays' in plugin CustomSprays v1.5.13 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`
	
Error for previous version
	`Console22:21:58
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Can't get CraftBukkit revision number! Only got 'org.bukkit.craftbukkit' instead.
at CustomSprays (1).jar/fun.LSDog.CustomSprays.util.NMS.getMcVer(NMS.java:46) ~[CustomSprays (1).jar:?]
at CustomSprays (1).jar/fun.LSDog.CustomSprays.util.NMS.getSubVer(NMS.java:54) ~[CustomSprays (1).jar:?]
at CustomSprays (1).jar/fun.LSDog.CustomSprays.util.NMS.getMcClass(NMS.java:293) ~[CustomSprays (1).jar:?]
at CustomSprays (1).jar/fun.LSDog.CustomSprays.util.NMS.<clinit>(NMS.java:69) ~[CustomSprays (1).jar:?]
... 13 more
INFO22:21:58
[CustomSprays]: Disabling CustomSprays v1.5.12
ERROR22:21:58
Error occurred while disabling CustomSprays v1.5.12
Console22:21:58
java.lang.NoClassDefFoundError: Could not initialize class fun.LSDog.CustomSprays.util.NMS
at CustomSprays (1).jar/fun.LSDog.CustomSprays.CustomSprays.onDisable(CustomSprays.java:43) ~[CustomSprays (1).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Can't get CraftBukkit revision number! Only got 'org.bukkit.craftbukkit' instead. [in thread "Server thread"]
at CustomSprays (1).jar/fun.LSDog.CustomSprays.util.NMS.getMcVer(NMS.java:46) ~[CustomSprays (1).jar:?]
at CustomSprays (1).jar/fun.LSDog.CustomSprays.util.NMS.getSubVer(NMS.java:54) ~[CustomSprays (1).jar:?]
at CustomSprays (1).jar/fun.LSDog.CustomSprays.util.NMS.getMcClass(NMS.java:293) ~[CustomSprays (1).jar:?]
at CustomSprays (1).jar/fun.LSDog.CustomSprays.util.NMS.<clinit>(NMS.java:69) ~[CustomSprays (1).jar:?]
at CustomSprays (1).jar/fun.LSDog.CustomSprays.CustomSprays.onEnable(CustomSprays.java:72) ~[CustomSprays (1).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]`

**Comment by LSDog** [comment]
I figured out what's happening, paper started to use mojang mapping instead of spigot mapping after 1.20.5, which makes my plugin (using spigot mapping names) can't properly use NMS with reflections, so there are few options:

- Don't use paper server, use spigot
- [Build a spigot mapping paper server jar](https://docs.papermc.io/paper/dev/userdev#spigot-mappings)

- I manually add every mojang mapping name (of fields methods classes...) to the code
- Other black magic to solve this (I didn't find it yet)

The first 2 options are for you if you really want to use CustomSprays plugin really quick, but I will definately find a way to make a universal plugin for both spigot & paper

**Comment by deadspidervenom** [comment]
Thanks for the options! I think Ill wait on 3. As paper from understanding is a more optimized spigot. At least that the TL;DR i could find online.

**Comment by LSDog** [comment]
hah, turns out I just need to fix the way of getting "rversion", paper will do the rest of translations automatically

**Comment by LSDog** [comment]
Fixed in [1.5.14](https://github.com/LSDog/CustomSprays/releases/tag/1.5.14) !
